POST /post HTTP/1.1
Host: httpbin.org
Connection: close
Accept: */*
User-Agent: Mozilla/4.0 (compatible; esp8266 micropython; Windows NT 5.1)
Content-Type: application/json
Content-Length: 278

{
    "data": 1234
}